name: "Rylan Schaeffer's Blog"
author:
  name: "Rylan Schaeffer"
  email: "rylanschaeffer@gmail.com"
  twitter: "RylanSchaeffer"
gems:
  - jekyll-feed

title: Rylan Schaeffer
description: "'So we seem to find, in our selves, unity over time, unity of function, unity in space'"
logo: index/profile_pic.jpg
show_downloads: false
google_analytics: UA-94033137-1
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  math_engine: mathjax
