name: "Rylan Schaeffer's Blog"
author:
  name: "Rylan Schaeffer"
  email: "rylanschaeffer@gmail.com"
  twitter: "RylanSchaeffer"
gems:
  - jekyll-feed

title: Rylan Schaeffer
description: "Of course it is happening inside your head, but why on earth should that mean that is not real?"
logo: index/profile_pic.png
show_downloads: false
google_analytics: UA-94033137-1
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  math_engine: mathjax
