name: "Rylan Schaeffer's Blog"
description: "Theoretical Neuroscience & Machine Learning"
author:
  name: "Rylan Schaeffer"
  email: "rylanschaeffer@gmail.com"
  twitter: "RylanSchaeffer"
gems:
  - jekyll-feed

title: Rylan Schaeffer
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  math_engine: mathjax
